apiVersion: v1
kind: Service
metadata:
  name: pod-resource-linter
  labels:
    app: pod-resource-linter
spec:
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pod-resource-linter